sudo: false

language: "java"

jdk:
- openjdk8

before_deploy:
  - git config --local user.name "Jeffrey Lee"
  - git config --local user.email "j.lee@intellijointsurgical.com"
  - git tag "Test6"

deploy:
  - provider: releases
    api_key: ${github_TravisCITest_api_key}
    file_glob: true
    file: "TravisCITest.jar"
    skip_cleanup: true
    name: "Test7"
    on:
        all_branches: true
        jdk: openjdk8
