sudo: false

language: "java"

jdk:
- openjdk8

before_deploy:
  - git config --local user.name "Jeffrey Lee"
  - git config --local user.email "j.lee@intellijointsurgical.com"
  - git tag "Test4"

deploy:
  - provider: releases
    api_key: ${github_TravisCITest_api_key}
    file_glob: true
    file: "release.zip"
    skip_cleanup: true
    name: "Test5"
    on:
        branch: 
        - main
        - Test2
        - Test3
        - Test4
        - Test5
        jdk: openjdk8
