sudo: false

language: "java"

jdk:
- openjdk8

before_deploy:
  - git config --local user.name "Jeffrey Lee"
  - git config --local user.email "j.lee@intellijointsurgical.com"
  - git tag "Test2"

deploy:
  - provider: releases
    api_key: ${github_TravisCITest_api_key}
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    name: "Test2"
    on:
        branch: 
        - main
        - Test2
        jdk: openjdk8
