sudo: false
dist: bionic

language: "java"

jdk:
- oraclejdk9
- oraclejdk13
- openjdk9
- openjdk13

script: "./gradlew clean build --rerun-tasks --scan" # gradle build runs test

before_deploy:
  - ./gradlew clean
  - ./gradlew jar
  - git config --local user.name "Jeffrey Lee"
  - git config --local user.email "j.lee@intellijointsurgical.com"
  - export NAME="v$(./gradlew version -q)"
  - git tag $NAME

deploy:
  - provider: releases
    api_key: ${github_TravisCITest_api_key}
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    name: $NAME
    on:
        branch: master
        jdk: oraclejdk9
